
apiVersion: v1
kind: Pod
metadata:
  name: secretexample
spec:
  containers:
  - name: secretexample
    image: busybox
    command:  [ "/bin/sh", "-c", "echo user name: $(USER)  customkey2: $(PASS) " ]
    env:
      - name: USER 
        valueFrom:
          secretKeyRef:
           name: webserver-credentials
           key:  username.txt
      - name:  PASS
        valueFrom:
          secretKeyRef:
           name: webserver-credentials
           key:  password.txt

